### PR TITLE
port of csharp client to fsharp client, issue #1

### PR DESCRIPTION
**Pull request by Arukim**
- all models ported
- runner, debug, MyStrategy ported
- .net 3.0 is used
- bot is working locally with the local runner
- utility scripts require validation from the org team

N.B. in F# order of files in the project is affecting the build process, so you need to keep it right.

### CODE REVIEW

**Comment by kuviman** [comment]
F# has sum types, which should be more idiomatic than inheritance for things like `Item`, right?

**Comment by Arukim** [comment]
> F# has sum types, which should be more idiomatic than inheritance for things like `Item`, right?

Updated sources with Discriminated Unions instead of classes inheritance.

**Comment by kuviman** [comment]
Is it possible to install both .Net Core version 2 and 3? (#3)

**Comment by Arukim** [comment]
Please, check my comment on this issue https://github.com/MailRuChamps/raic-2019/pull/3#issuecomment-560350126
Dockerfiles would be a problem, so it is better to stick with a single version.

**Comment by kuviman** [comment]
Regarding sum types: is there specific reason that `Item`'s type is actually `Item.T` instead of just `Item`?
Are modules necessary here, or can we just write

`type Item = HealthPack of HealthPackItem | Mine of MineItem ...`

In any case, we are currently adopting this to autogeneration so that F# will be available next time. Should be added soon

**Comment by Arukim** [comment]
Item is placed inside a module to mimic other languages (C#) structure where Item-related entities are placed inside Item. This causes this ad hoc T type which is used to denote Item itself. Which seems to be common practice in F# for handling such cases.
We can get rid of the Item module and T type inside it by placing both Item and sub-items in the root namespace AiCup2019.Model. The only drawback - we need to keep things in the root namespace unique. Feel free to use this paradigm since using Item.T in code seems a bit weird.

I'm glad that the port is coming to the official package soon.

**Comment by kuviman** [comment]
It's probably better to mimic languages that do support ADTs, like [Rust](https://github.com/MailRuChamps/raic-2019/blob/master/clients/rust/model/src/item.rs). More idiomatic the solution is for F# the better.

I'm guessing the difference here is that each variant does need to be of its own type in F# though, right?

**Comment by kuviman** [comment]
`error FS0525: An integer for loop must use a simple identifier`

Is this something that works only with .Net Core 3?

**Comment by Arukim** [comment]
> `error FS0525: An integer for loop must use a simple identifier`
> 
> Is this something that works only with .Net Core 3?

Just made a quick test on my machine (win) - I don't get any errors when downgrading framework version to 2.1 / 2.0

Does this problem happen on a generated code or on the provided sample code? Can you kindly provide error location?

**Comment by Arukim** [comment]
> I'm guessing the difference here is that each variant does need to be of its own type in F# though, right?
I suppose so, you need to provide Type implementation. Anyway, I'm not an expert in F#, so any solution is welcome.

**Comment by kuviman** [comment]
This happens on both. Anyway, seems like I've fixed it with using `for _ in a..b` syntax instead.

Also, due to autogeneration, we got a lot of indentation warnings, but suppressing them with `#nowarn "0058"` works.

So, we have a working F# client now. We can allow submitting with .Net Core 2.1 now, but we would want to support .Net Core 3 also. Help with #3 would be appreciated.

**Pull request closed without merging**
