### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by dzkisialiou**
This attribute is called 'type' in the docs

### CODE REVIEW

**Comment by stulentsev** [comment]
It's not a typo, though (I think). The parameter is matching the property name (which has reasons to be named `typ`). There's value in that.

**Comment by dzkisialiou** [comment]
It still doesn't match with documentation,

**Comment by stulentsev** [comment]
@dzkisialiou fair enough. FWIW, I think it's the documentation that needs to be fixed.

**Comment by kuviman** [comment]
This is due to autogeneration and `type` being keyword in some languages. You can change it in your code if you want.

**Pull request closed without merging**
