### PR TITLE
Update .net core to 3.0

### PR DESCRIPTION
**Pull request by MelnikovIG**

### CODE REVIEW

**Comment by kuviman** [comment]
Is it possible to install both .net core 2 and 3 to make all current submissions still work?

```sh
$ dotnet aicup2019.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

**Comment by Arukim** [comment]
> Is it possible to install both .net core 2 and 3 to make all current submissions still work?

I think it is cumbersome due to the framework-specific docker files. See the first line of the docker file. Since those files are handled on the server-side we can have only one compiler version support.

Don't current submissions use already built docker files? In this case, they would survive the version update. So switching to 3.0 should break only new submissions -> everyone should upgrade to core 3.0.

**Comment by kuviman** [comment]
If it is possible to install both versions on your system, it should be possible to do so in Docker.

If you look at `compile.sh`, you'll see that we copy output to `/output` directory which is stored outside docker, so if we update `Dockerfile` to support both versions, old submissions should still work

**Comment by Arukim** [comment]
Problem is that the multi-version base image isn't provided by MS. So you need to modify one to do so. And it will be better to do this only once and store the resulting 'build' image in some registry to not to repeat the same steps for each build.
Sample of adding extra language can be found here:
https://stackoverflow.com/questions/55013915/multiple-dotnet-core-versions-on-linux-docker-image

**Comment by kuviman** [comment]
Docker image is actually built only once. The only thing that happens each build is running `compile.sh`

> Sample of adding extra language can be found here:
https://stackoverflow.com/questions/55013915/multiple-dotnet-core-versions-on-linux-docker-image

So, it is possible after all, right? Can we have a PR that modifies `Dockerfile` as needed then?

**Comment by Arukim** [comment]
@kuviman, Let me share a working solution, this one gives a docker container that has both LTS(2.1) and Current(3.0) versions onboard.

[Dockerfile.txt](https://github.com/MailRuChamps/raic-2019/files/3917403/Dockerfile.txt)

**Comment by Arukim** [comment]
prepared a separate PR https://github.com/MailRuChamps/raic-2019/pull/53

**Comment by kuviman** [comment]
Closing this in favor of #53

**Pull request closed without merging**
